### PR TITLE
Normative: Only display negative signs on the largest unit when formatting negative Durations

### PR DESCRIPTION
**Pull request by ben-allen**
fix #169

### CODE REVIEW

**Review by sffc — APPROVED** [review]

**Comment by sffc** [comment]
TG2 approval: https://github.com/tc39/ecma402/blob/master/meetings/notes-2023-11-16.md#format-of-negative-durations-169

**Comment by ryzokuken** [comment]
2023-11-28: This PR achieved TC39-TG1 consensus.

**Comment by FrankYFTang** [comment]
Do we have a test for this?

**Comment by FrankYFTang** [comment]
The following tests in test262 need to be updated after the landing of the PR

test262/intl402/DurationFormat/prototype/format/negative-duration-style-default-en
test262/intl402/DurationFormat/prototype/format/negative-durationstyle-long-en
test262/intl402/DurationFormat/prototype/format/negative-durationstyle-digital-en
test262/intl402/DurationFormat/prototype/format/negative-durationstyle-narrow-en
test262/intl402/DurationFormat/prototype/format/negative-duration-style-short-en
test262/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-digital-en
test262/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-long-en
test262/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-narrow-en
test262/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-short-en
test262/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-default-en

**Pull request merged**
