### PR TITLE
Add v8 prototype info

### PR DESCRIPTION
**Pull request by FrankYFTang**

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@younies @sffc @ryzokuken @zbraniecki

**Review by zbraniecki — APPROVED** [review]

**Comment by FrankYFTang** [comment]
I have no commit right, someone have to submit for me

**Comment by FrankYFTang** [comment]
I added info of my second prototype based on LNF as well as ICU related tickets

**Review by younies — APPROVED** [review]

**Comment by FrankYFTang** [comment]
I don't have the merge access so someone need to click the merge button for me. Thanks

**Pull request merged**
