### PR TITLE
Normative: Revert to previous behaviour by setting fallback value for fractionalDigits to *undefined*

### LINKED ISSUE #149: Default fractional digits no longer displayed after #113
I've missed this in the review for #113, but the changes from #113 actually also changed the format output. For example:
```js
new Intl.DurationFormat("en", {seconds: "numeric"}).format({seconds: 1, milliseconds: 3})
```

Returned `"1.003"` before #113, but is now returning `"1"`.

It was returning `"1.003"`, because when `fractionalDigits = undefined` was passed to the `Intl.NumberFormat`, the default minimum and maximum fractional digits from `Intl.NumberFormat` were applied. (`mnfdDefault = 0` and `mxfdDefault = 3` in [InitializeNumberFormat](https://tc39.es/ecma402/#sec-initializenumberformat).)

#144 may resolve this issue anyway, but I still thought it's worthwhile to file an issue about it.

### PR DESCRIPTION
**Pull request by ben-allen**
Fix #149 Fix #144

### CODE REVIEW

**Comment by sffc** [comment]
Two issues:

1. Please note in "Properties of Intl.DurationFormat Instances" that the field can be undefined.
2. We should pass 0/9 into Intl.NumberFormat instead of undefined/undefined in PartitionDurationFormatPattern

**Comment by anba** [comment]
[Intl.DurationFormat.prototype.resolvedOptions](https://tc39.es/proposal-intl-duration-format/#sec-Intl.DurationFormat.prototype.resolvedOptions) currently asserts that all internal slots have a non-undefined value. This is no longer true if `[[FractionalDigits]]` can be undefined. 

I guess an undefined `[[FractionalDigits]]` should be omitted from the output for consistency with the other `resolvedOptions` methods, even though undefined for `[[FractionalDigits]]` has a different meaning when compared to undefined internal slots for the other Intl service constructors.

**Comment by anba** [comment]
I also wonder if the entries in [Resolved Options of DurationFormat Instances](https://tc39.es/proposal-intl-duration-format/#table-durationformat-resolvedoptions-properties) should be reordered if an undefined `[[FractionalDigits]]` is omitted, so that the optional `[[FractionalDigits]]` appears last. For example by moving `[[NumberingSystem]]` to the top, see also [Resolved Options of DateTimeFormat Instances](https://tc39.es/ecma402/#table-datetimeformat-resolvedoptions-properties) and [Resolved Options of NumberFormat Instances](https://tc39.es/ecma402/#table-numberformat-resolvedoptions-properties).

**Review by ryzokuken — APPROVED** [review]
There was also the suggestion of reordering the `resolvedOptions`, but I think it's something we can build consensus on this evening.

**Review by sffc — APPROVED** [review]

**Comment by FrankYFTang** [comment]
This PR reach TC39 consensus in July 12, 2023

**Comment by ryzokuken** [comment]
Thanks for the update @FrankYFTang! I'll rebase and merge later this week.

**Comment by FrankYFTang** [comment]
Could we add some test to test262 to validate the change of this PR?

**Comment by FrankYFTang** [comment]
@sffc @ben-allen @ryzokuken 
I do not belive the part of reordering the order of resolvedOptions to move "numberingSystem" to the top reach any consensus. The title of this PR has nothing to do with  that and somehow that reordering to merged under this PR without TG2 discussion nor TG1 consensus. Please revert that change. 

@ben-allen this PR is already merged to the trunk, you merge your restoration into your branch of this PR after the merging which will not fix the trunk.

The landing of this PR seems very very troublesome . it include part which we didn't discuss

The landing of this PR includes 4 commits according to
https://github.com/tc39/proposal-intl-duration-format/pull/150/commits

https://github.com/tc39/proposal-intl-duration-format/pull/150/commits/df63a06430e24069527731cf03c18536962fdb66
https://github.com/tc39/proposal-intl-duration-format/pull/150/commits/4b9a46a584e8c57046df2abe3197e53a8b485e80
https://github.com/tc39/proposal-intl-duration-format/pull/150/commits/e4774b0960a65e5176d24d59773b43c5e8f5c212
I believe these 3 are ok

https://github.com/tc39/proposal-intl-duration-format/pull/150/commits/32950ea74084350168c19712fc30752f30d01505
this is a troublesome change, it chagne two thing- it perform some necessary change for the above 3 commits but ALSO include the reordering change of numberingSystem in the resolvedOption
this later was never communicate and agree upon TG2 members and never mentioned to TG1 members.

I beleve our edtior should revert that part of the change (the order of numberingSystem in resolvedOption should not be on the top ASAP since that was a technical error for merging something we never agree upon. If we in deed want to reoder that. That need a Normative PR to be discuss in TG2 and also TG1.

**Pull request merged**
