### PR TITLE
Add github workflow to automatic build the index.html

### PR DESCRIPTION
**Pull request by FrankYFTang**
Try to fix https://github.com/tc39/proposal-intl-duration-format/issues/24

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@ryzokuken @younies

**Review by ryzokuken — CHANGES_REQUESTED** [review]
A few concerns: 

1. Should it only run on master?
2. Should it push to the `gh-pages` branch instead of adding new commits to the master branch?
3. If not, what should the message of the commit be?

**Comment by FrankYFTang** [comment]
I am just copy from those in https://github.com/tc39/proposal-intl-locale-info which I clone from proposal 10 months ago. I have problem to make it auto build before. I do not have the answer for you. You can see how it work on https://github.com/tc39/proposal-intl-locale-info and neither I am sure I put all enough thing here.

**Comment by FrankYFTang** [comment]
notice https://github.com/tc39/proposal-intl-duration-format/pull/51/commits/e5500336da7b1a961541c67e91c34d43351850a5 is automatically added to the PR by the build.yml file - which is the point...

**Comment by ljharb** [comment]
The proposal template has the spec published from the default branch (_not_ the gh-pages branch) and so its Action workflow updates the default branch/PRs directly.

It's nice when the PRs themselves are updated, so that every other commit on master isn't "update spec".

**Comment by FrankYFTang** [comment]
I figure I also need to add 
location: https://tc39.es/proposal-intl-duration-format/ 
to the spec.emu

**Comment by FrankYFTang** [comment]
@younies @sffc

**Comment by FrankYFTang** [comment]
@younies  this may automatically resolve the out of sycn between spec.emu and index.html for you.

**Pull request merged**
