### PR TITLE
Reorder observable field access

### PR DESCRIPTION
**Pull request by ptomato**
This addresses the discrepancy in observable property access order in ToDurationRecord between this proposal and Temporal.

Closes: #95

### CODE REVIEW

**Review by ryzokuken — APPROVED** [review]
LGTM overall. I see you removed a few validations here and there: were those redundant?

**Comment by ptomato** [comment]
> I see you removed a few validations here and there: were those redundant?

Those were required to be removed by the new version of ecmarkup. (The operations don't return a completion record.)

**Comment by romulocintra** [comment]
Hey @FrankYFTang  can you give it a look

**Review by FrankYFTang — APPROVED** [review]
LGTM. Thanks for working on this.

**Comment by FrankYFTang** [comment]
sorry for my late reponse. I was on two weeks vacation following by slow recovering from COVID sickness when this was first proprosed. Great Job!

**Pull request merged**
