### PR TITLE
Update ecmarkup and publish spec

### PR DESCRIPTION
**Pull request by ryzokuken**
Will look into the build pipeline in a bit.

### CODE REVIEW

**Review by FrankYFTang — COMMENTED** [review]
I am very confused here. What you need to so to update the spec text is to change spec.emu and review spec.emu and put that into a PR and the build process will automatically build the index.html for you. We should not review index.html in the PR. spec.emu should be the source of truth, not index.html

**Comment by FrankYFTang** [comment]
@sffc

**Comment by ljharb** [comment]
Updating ecmarkup would cause diffs in index.html, but not in spec.emu; this is expected.

You may want to use the infra in the proposal template, which builds automatically for you.

**Comment by FrankYFTang** [comment]
oh... I see, so you are just updating the version of ecmarkup. Sorry for my misunderstanding.

**Review by FrankYFTang — APPROVED** [review]

**Comment by ryzokuken** [comment]
@ljharb @FrankYFTang I manually rebuilt index.html and therefore the diff changes came into this PR. If you want, I can drop those changes and let CI do them automatically.

**Comment by FrankYFTang** [comment]
no, you don't need to do that. I was just confused. I thought you were manually changing index.html but not spec.emu . But you are just changing the version number and regenerate the index.html. It is ok you check in index.html, and check in with it. Not a big deal.

**Comment by FrankYFTang** [comment]
I just don't want to miss anything which should be in spec.emu

**Comment by ryzokuken** [comment]
@FrankYFTang got it, that makes sense. I that case, I will merge this.

**Pull request merged**
